### ISSUE TITLE
Set number of possible concurrent sessions

### ISSUE THREAD

**Issue by Kuzovlev-Sanya** [fjarrett/prevent-concurrent-logins#9]
Is it possible to set the allowed number of concurrent sessions? For instance 2 for all users?

**Comment by frankiejarrett** [comment]
Hi @Kuzovlev-Sanya,

I get this question a lot, and the short answer is: No.

The longer answer is that WordPress doesn't make this easy to do because it doesn't have a method to "destroy this particular session". I'm certainly not ruling out the possibility of adding something like this, especially if core improves the API, but as of now I have no plans.

cf.
https://wordpress.org/support/topic/set-max-amount-of-concurrent-logins/
https://wordpress.org/support/topic/limit-to-a-set-amount-of-concurrent-logins/
https://wordpress.org/support/topic/control-concurrent-logins/

**Comment by Kuzovlev-Sanya** [comment]
Hi, why not get all user session with [get_sessions](https://developer.wordpress.org/reference/classes/wp_user_meta_session_tokens/get_sessions/) sort them by expiration date and destroy unwelcome by passing only session verifier to [update_session](https://developer.wordpress.org/reference/classes/wp_user_meta_session_tokens/update_session/) (according to docs if you skip $session argument than session will be destroyed)

**Comment by frankiejarrett** [comment]
@Kuzovlev-Sanya because `update_session()` is only protected and not exposed anywhere in the public API :-) If you know of a way around that please share!
